var catalog = [     //create products total 9
{
    _id: "boardShorts",
    title: "Board Shorts",
    category: "shorts",
    price: 15.99,
    image: "/images/boardShorts.jpeg",//from product folder in public
    minimum: 1,
},
{
    _id: "tanT",
    title: "Tan T-Shirt",
    category: "shirt",
    price: 10.00,
    image:"/images/blackShirt.jpeg",
    minimum: 1,
},
{
    _id: "gymShortsOne",
    title: " Gym Shorts White",
    category: "shorts",
    price: 6.99,
    image:"/images/whiteShort.jpeg",
    minimum: 1,
},
{
    _id: "longSleeve",
    title: " Long Sleeve",
    category: "shirts",
    price: 8.99,
    image:"/images/longSleeve.jpeg",
    minimum: 1, 
},
{
    _id: "swimSuit",
    title: " Swim Trunks",
    category: "shorts",
    price: 5.99,
    image:"/images/swimTrunks.jpeg",
    minimum: 1,
},
{
    _id: "tankTop",
    title: " Tank Top",
    category: "tankTop",
    price: 5.99,
    image:"/images/tankTop.jpeg",
    minimum: 1,
},
{
    _id: "gymShortsBlack",
    title: " Gym Shorts Black",
    category: "shorts",
    price: 6.99,
    image:"/images/blackShorts.jpeg",
    minimum: 1,
},
{
    _id: "gymShortsRed",
    title: " Gym Shorts Red",
    category: "shorts",
    price: 6.99,
    image:"/images/redShorts.jpeg",
    minimum: 1,
},
{
    _id: "SunGlasses",
    title: " Sun Glasses",
    category: "glasses",
    price: 30.00,
    image:"/images/glasses",
    minimum: 1,
},

];

